on:
  release:
    types: [prereleased, released]

name: Deploy Extension
jobs:
  publish-extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          ## make sure this corresponds with the version in test.yml
          node-version: latest
      - run: yarn install --immutable --immutable-cache --check-cache

      - name: Package Extension
        id: packageExtension
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: stub
          dryRun: true
          preRelease: ${{ github.event.action == 'prereleased' }}
          yarn: true

      ## Make sure the artifact is added to the release.
      - name: Upload extension vsix to workflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: haskell-${{ github.event.release.tag_name }}.vsix
          path: ${{ steps.packageExtension.outputs.vsixPath }}

      ## If this is a release job, publish to VSCode Marketplace,
      ## otherwise publish a pre-release to VSCode Marketplace
      - name: Publish to Visual Studio Marketplace
        id: publishToVSMarketplace
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          extensionFile: ${{ steps.packageExtension.outputs.vsixPath }}
          yarn: true
          preRelease: ${{ github.event.action == 'prereleased' }}

      ## If this is a release job, publish to VSX Marketplace,
      ## otherwise publish a pre-release to VSX Marketplace
      - name: Publish to Open VSX Registry
        id: publishToOpenVSX
        continue-on-error: true
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          extensionFile: ${{ steps.packageExtension.outputs.vsixPath }}
          yarn: true
          preRelease: ${{ github.event.action == 'prereleased' }}
