on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        ghc: [8.10.7, 9.6.7, 9.8.4, 9.12.2]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          ## make sure this corresponds with the version in release.yml
          node-version: latest

      # Install test dependencies
      - run: npm ci
      - run: npm run webpack

      # Setup toolchains, install ghcup, install ghc, etc...
      - name: Install GHCup
        uses: haskell/ghcup-setup@v1
        with:
          ghc: ${{ matrix.ghc }}
          cabal: latest
          stack: latest

      - name: Install HLS 2.2 and latest
        run: |
          ghcup install hls 2.2.0.0
          ghcup install hls latest
        shell: bash

      # Run the tests
      - name: Run the test on Linux
        run: |
          xvfb-run -s '-screen 0 640x480x16' -a npm run test
        shell: bash
        if: runner.os == 'Linux'
      - name: Run the test on macOS
        run: |
          npm run test
        shell: bash
        if: runner.os == 'macOS'
      - name: Run the test on Windows
        run: |
          npm run test
        shell: bash
        if: runner.os == 'Windows'
